INSERT INTO railways (id, city, railway_address) VALUES ('1',  'Wroclaw','ul. Joannitow 13');
INSERT INTO railways (id, city, railway_address) VALUES ('2',  'Bydgoszcz','ul. Torunska 147');
INSERT INTO railways (id, city, railway_address) VALUES ('3',  'Lublin','Aleje Tysiaclecia 6');
INSERT INTO railways (id, city, railway_address) VALUES ('4',  'Gorzow Wielkopolski','Dworcowa 10');
INSERT INTO railways (id, city, railway_address) VALUES ('5',  'Lodz', 'PKP Karolewska 55');
INSERT INTO railways (id, city, railway_address) VALUES ('6',  'Krakow','Bosacka 18');
INSERT INTO railways (id, city, railway_address) VALUES ('7',  'Warszawa','Aleje Jerozolimskie 54');
INSERT INTO railways (id, city, railway_address) VALUES ('8',  'Opole','1 Maja 4');
INSERT INTO railways (id, city, railway_address) VALUES ('9',  'Rzeszow','Artura Grottgera 1');
INSERT INTO railways (id, city, railway_address) VALUES ('10', 'Bialystok','Bohaterow Monte Cassino 10');
INSERT INTO railways (id, city, railway_address) VALUES ('11', 'Gdansk', '3 Maja 12' );
INSERT INTO railways (id, city, railway_address) VALUES ('12', 'Katowice','Skargi 1' );
INSERT INTO railways (id, city, railway_address) VALUES ('13', 'Kielce','ul. Czarnowska 12');
INSERT INTO railways (id, city, railway_address) VALUES ('14', 'Olsztyn','plac Konstytucji 3 Maja 2A ');
INSERT INTO railways (id, city, railway_address) VALUES ('15', 'Poznan','Stanislawa Matyi 2');
INSERT INTO railways (id, city, railway_address) VALUES ('16', 'Szczecin','plac Grodnicki 1' );
